export const COMPLETE_REGISTRATION_LOADING = 'COMPLETE_REGISTRATION_LOADING';
export const COMPLETE_REGISTRATION_SUCCESS = 'COMPLETE_REGISTRATION_SUCCESS';
export const COMPLETE_REGISTRATION_FAIL = 'COMPLETE_REGISTRATION_FAIL';

export const  UPDATEE_USER_DETAILS_LOADING = 'UPDATEE_USER_DETAILS_LOADING';
export const UPDATEE_USER_DETAILS_SUCCESS = 'UPDATEE_USER_DETAILS_SUCCESS';
export const UPDATEE_USER_DETAILS_FAIL = 'UPDATEE_USER_DETAILS_FAIL';
