export const COMPLETE_REGISTRATION_LOADING = 'COMPLETE_REGISTRATION_LOADING';
export const COMPLETE_REGISTRATION_SUCCESS = 'COMPLETE_REGISTRATION_SUCCESS';
export const COMPLETE_REGISTRATION_FAIL = 'COMPLETE_REGISTRATION_FAIL';
