export const UPDATE_EMAIL_AND_PASSWORD_LOADING = 'UPDATE_EMAIL_AND_PASSWORD_LOADING';
export const UPDATE_EMAIL_AND_PASSWORD_SUCCESS = 'UPDATE_EMAIL_AND_PASSWORD_SUCCESS';
export const UPDATE_EMAIL_AND_PASSWORD_FAIL = 'UPDATE_EMAIL_AND_PASSWORD_FAIL';
